import React from 'react'
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
    title: "About page",
    description: "Generated by create next app",
  };

const About = () => {
    // throw new Error("A fictional error 😎");
  return (
    <>
        <h1>About page</h1>
        <Link href={'/'}>return to root</Link>
    </>
  )
}

export default About